#!/bin/bash

#Vars
HW='-y -hide_banner -threads 8 -hwaccel nvdec -hwaccel_output_format cuda'
OPT='-preset slow -flags +loop -cmp chroma -subq 6 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -b_strategy 1'
TITLES='-metadata title'
DESC='-metadata description'
COMM='-metadata comment'
LINGUA='-map 0:v -map 0:m:language:ita'

# Windows dialog
HEIGHT=15
WIDTH=60
CHOICE_HEIGHT=5
BACKTITLE="Converi i tuoi file video"
TITLE="Converti i file in diversi formati: 480p - 720p - 1080p"
MENU="Scegli in quale formato vuoi converire:"

OPTIONS=(1 "Converti in 480p"
         2 "Converti in 720p"
         3 "Converti in 720p con AC5.1"
	 4 "Converti in 1080p"
	 5 "Converti in 1080 con AC5.1")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)
clear

case $CHOICE in
  1)
    echo "Hai scelto 480p"
    H=480
    DEST_DIR=`basename "$PWD"-480p`
    AOP='-acodec aac -strict experimental -ar 44100 -b:a 64k'
    VOP='-c:v h264_nvenc -rc vbr -minrate 500k -maxrate 2M -bufsize 2M'
    mkdir -p ../"$DEST_DIR"
    for i in *.{mp4,ts,mov,wmv,mpg,avi,mkv}; do
      FF_TITLE="${i%%.*}"
      FF_DESC=`basename "$PWD"`
      ffmpeg $HW -i "$i" -vf scale_cuda=-1:$H $VOP $AOP $OPT $LINGUA $TITLES="$FF_TITLE" $DESC="$FF_DESC" $COMM="$FF_DESC" "../$DEST_DIR/${i%.*}.mp4";
    done
    ;;
  2)
    echo "Hai scelto 720p"
    H=720
    DEST_DIR=`basename "$PWD"-720p`
    AOP='-acodec aac -strict experimental -ar 48000 -b:a 640k'
    VOP='-c:v h264_nvenc -rc vbr_hq -profile:v main -minrate 1500k -maxrate 4M -bufsize 5M'
    mkdir -p ../"$DEST_DIR"
    for i in *.{mp4,ts,mov,wmv,mpg,avi,mkv}; do
      FF_TITLE="${i%%.*}"
      FF_DESC=`basename "$PWD"`
      ffmpeg $HW -i "$i" -vf scale_cuda=-1:$H $VOP $AOP $OPT $LINGUA $TITLES="$FF_TITLE" $DESC="$FF_DESC" $COMM="$FF_DESC" "../$DEST_DIR/${i%.*}.mp4";
    done
    ;;
  3)
    echo "Hai scelto 720p con AC 5.1"
    H=720
    DEST_DIR=`basename "$PWD"-720p`
    AOP='-acodec ac3 -ac 6 -strict experimental -ar 48000 -b:a 640k'
    VOP='-c:v h264_nvenc -rc vbr_hq -profile:v main -minrate 1500k -maxrate 4M -bufsize 5M'
    mkdir -p ../"$DEST_DIR"
    for i in *.{mp4,ts,mov,wmv,mpg,avi,mkv}; do
      FF_TITLE="${i%%.*}"
      FF_DESC=`basename "$PWD"`
      ffmpeg $HW -i "$i" -vf scale_cuda=-1:$H $VOP $AOP $OPT $LINGUA $TITLES="$FF_TITLE" $DESC="$FF_DESC" $COMM="$FF_DESC" "../$DEST_DIR/${i%.*}.mp4";
    done
    ;;
  4)
    echo "Hai scelto 1080p"
    H=1080
    DEST_DIR=`basename "$PWD"-1080p`
    AOP='-acodec aac -strict experimental -ar 48000 -b:a 1536k'
    VOP='-c:v h264_nvenc -rc vbr_hq -profile:v main -minrate 3500k -maxrate 9M -bufsize 9M'
    mkdir -p ../"$DEST_DIR"
    for i in *.{mp4,ts,mov,wmv,mpg,avi,mkv}; do
      FF_TITLE="${i%%.*}"
      FF_DESC=`basename "$PWD"`
     ffmpeg $HW -i "$i" -vf scale_cuda=-1:$H $VOP $AOP $OPT $LINGUA $TITLES="$FF_TITLE" $DESC="$FF_DESC" $COMM="$FF_DESC" "../$DEST_DIR/${i%.*}.mp4";
    done
    ;;
  5)
    echo "Hai scelto 1080p con AC 5.1"
    H=1080
    DEST_DIR=`basename "$PWD"-1080p`
    AOP='-acodec ac3 -ac 6 -strict experimental -ar 48000 -b:a 1536k'
    VOP='-c:v h264_nvenc -rc vbr_hq -profile:v main -minrate 3500k -maxrate 9M -bufsize 9M'
    mkdir -p ../"$DEST_DIR"
    for i in *.{mp4,ts,mov,wmv,mpg,avi,mkv}; do
      FF_TITLE="${i%%.*}"
      FF_DESC=`basename "$PWD"`
     ffmpeg $HW -i "$i" -vf scale_cuda=-1:$H $VOP $AOP $OPT $LINGUA $TITLES="$FF_TITLE" $DESC="$FF_DESC" $COMM="$FF_DESC" "../$DEST_DIR/${i%.*}.mp4";
    done
    ;;
esac
